version: "3.9"
   
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=reallyStrongPwd123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9876
    volumes:
    - .:/code
    ports:
      - "9876:9876"
    depends_on:
      - db