USE [master]
GO

/****** Object:  Database [IEL_Estagio_PRD]    Script Date: 20/10/2021 11:57:48 ******/
CREATE DATABASE [IEL_Estagio_PRD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IEL_Estagio_PRD_Data', FILENAME = N'/var/opt/mssql/data\IEL_Estagio_PRD.mdf' , SIZE = 12288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'IEL_Estagio_PRD_Log', FILENAME = N'/var/opt/mssql/data\IEL_Estagio_PRD.ldf' , SIZE = 23616KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IEL_Estagio_PRD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IEL_Estagio_PRD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET ARITHABORT OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET  ENABLE_BROKER 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET RECOVERY FULL 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET  MULTI_USER 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IEL_Estagio_PRD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IEL_Estagio_PRD] SET QUERY_STORE = OFF
GO

ALTER DATABASE [IEL_Estagio_PRD] SET  READ_WRITE 
GO

